// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __hypergeo_h__
#define __hypergeo_h__

#include "hypergeo_RcppExports.h"

#endif // __hypergeo_h__
