// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/hypergeo.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// complex_lngamma
arma::cx_vec complex_lngamma(const arma::cx_vec z);
static SEXP hypergeo_complex_lngamma_try(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const arma::cx_vec >::type z(zSEXP);
    __result = Rcpp::wrap(complex_lngamma(z));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP hypergeo_complex_lngamma(SEXP zSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(hypergeo_complex_lngamma_try(zSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// complex_lngamma_cpp
Rcpp::ComplexVector complex_lngamma_cpp(const Rcpp::NumericVector& real, const Rcpp::NumericVector& imag);
static SEXP hypergeo_complex_lngamma_cpp_try(SEXP realSEXP, SEXP imagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type real(realSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type imag(imagSEXP);
    __result = Rcpp::wrap(complex_lngamma_cpp(real, imag));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP hypergeo_complex_lngamma_cpp(SEXP realSEXP, SEXP imagSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(hypergeo_complex_lngamma_cpp_try(realSEXP, imagSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// genhypergeo_series
arma::cx_vec genhypergeo_series(const arma::cx_vec U, const arma::cx_vec L, arma::cx_vec z, const double tol, const int maxiter, const bool check_mod, const bool polynomial);
static SEXP hypergeo_genhypergeo_series_try(SEXP USEXP, SEXP LSEXP, SEXP zSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP check_modSEXP, SEXP polynomialSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const arma::cx_vec >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::cx_vec >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::cx_vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_mod(check_modSEXP);
    Rcpp::traits::input_parameter< const bool >::type polynomial(polynomialSEXP);
    __result = Rcpp::wrap(genhypergeo_series(U, L, z, tol, maxiter, check_mod, polynomial));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP hypergeo_genhypergeo_series(SEXP USEXP, SEXP LSEXP, SEXP zSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP check_modSEXP, SEXP polynomialSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(hypergeo_genhypergeo_series_try(USEXP, LSEXP, zSEXP, tolSEXP, maxiterSEXP, check_modSEXP, polynomialSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// genhypergeo_series_cpp
Rcpp::ComplexVector genhypergeo_series_cpp(const Rcpp::NumericVector& real_U, const Rcpp::NumericVector& imag_U, const Rcpp::NumericVector& real_L, const Rcpp::NumericVector& imag_L, const Rcpp::NumericVector& real_z, const Rcpp::NumericVector& imag_z, const double tol, const int maxiter, const bool check_mod, const bool polynomial);
static SEXP hypergeo_genhypergeo_series_cpp_try(SEXP real_USEXP, SEXP imag_USEXP, SEXP real_LSEXP, SEXP imag_LSEXP, SEXP real_zSEXP, SEXP imag_zSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP check_modSEXP, SEXP polynomialSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type real_U(real_USEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type imag_U(imag_USEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type real_L(real_LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type imag_L(imag_LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type real_z(real_zSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type imag_z(imag_zSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_mod(check_modSEXP);
    Rcpp::traits::input_parameter< const bool >::type polynomial(polynomialSEXP);
    __result = Rcpp::wrap(genhypergeo_series_cpp(real_U, imag_U, real_L, imag_L, real_z, imag_z, tol, maxiter, check_mod, polynomial));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP hypergeo_genhypergeo_series_cpp(SEXP real_USEXP, SEXP imag_USEXP, SEXP real_LSEXP, SEXP imag_LSEXP, SEXP real_zSEXP, SEXP imag_zSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP check_modSEXP, SEXP polynomialSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(hypergeo_genhypergeo_series_cpp_try(real_USEXP, imag_USEXP, real_LSEXP, imag_LSEXP, real_zSEXP, imag_zSEXP, tolSEXP, maxiterSEXP, check_modSEXP, polynomialSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// lanczos
arma::cx_vec lanczos(arma::cx_vec z);
static SEXP hypergeo_lanczos_try(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::cx_vec >::type z(zSEXP);
    __result = Rcpp::wrap(lanczos(z));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP hypergeo_lanczos(SEXP zSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(hypergeo_lanczos_try(zSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// lanczos_cpp
Rcpp::ComplexVector lanczos_cpp(const Rcpp::NumericVector& real, const Rcpp::NumericVector& imag);
static SEXP hypergeo_lanczos_cpp_try(SEXP realSEXP, SEXP imagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type real(realSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type imag(imagSEXP);
    __result = Rcpp::wrap(lanczos_cpp(real, imag));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP hypergeo_lanczos_cpp(SEXP realSEXP, SEXP imagSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(hypergeo_lanczos_cpp_try(realSEXP, imagSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}

// validate (ensure exported C++ functions exist before calling them)
static int hypergeo_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::cx_vec(*complex_lngamma)(const arma::cx_vec)");
        signatures.insert("Rcpp::ComplexVector(*complex_lngamma_cpp)(const Rcpp::NumericVector&,const Rcpp::NumericVector&)");
        signatures.insert("arma::cx_vec(*genhypergeo_series)(const arma::cx_vec,const arma::cx_vec,arma::cx_vec,const double,const int,const bool,const bool)");
        signatures.insert("Rcpp::ComplexVector(*genhypergeo_series_cpp)(const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const double,const int,const bool,const bool)");
        signatures.insert("arma::cx_vec(*lanczos)(arma::cx_vec)");
        signatures.insert("Rcpp::ComplexVector(*lanczos_cpp)(const Rcpp::NumericVector&,const Rcpp::NumericVector&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP hypergeo_RcppExport_registerCCallable() { 
    R_RegisterCCallable("hypergeo", "hypergeo_complex_lngamma", (DL_FUNC)hypergeo_complex_lngamma_try);
    R_RegisterCCallable("hypergeo", "hypergeo_complex_lngamma_cpp", (DL_FUNC)hypergeo_complex_lngamma_cpp_try);
    R_RegisterCCallable("hypergeo", "hypergeo_genhypergeo_series", (DL_FUNC)hypergeo_genhypergeo_series_try);
    R_RegisterCCallable("hypergeo", "hypergeo_genhypergeo_series_cpp", (DL_FUNC)hypergeo_genhypergeo_series_cpp_try);
    R_RegisterCCallable("hypergeo", "hypergeo_lanczos", (DL_FUNC)hypergeo_lanczos_try);
    R_RegisterCCallable("hypergeo", "hypergeo_lanczos_cpp", (DL_FUNC)hypergeo_lanczos_cpp_try);
    R_RegisterCCallable("hypergeo", "hypergeo_RcppExport_validate", (DL_FUNC)hypergeo_RcppExport_validate);
    return R_NilValue;
}
