# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complex_gamma <- function(z) {
    .Call('hypergeo_complex_gamma', PACKAGE = 'hypergeo', z)
}

complex_gamma_cpp <- function(real, imag) {
    .Call('hypergeo_complex_gamma_cpp', PACKAGE = 'hypergeo', real, imag)
}

genhypergeo_series <- function(U, L, z, tol, maxiter, check_mod, polynomial) {
    .Call('hypergeo_genhypergeo_series', PACKAGE = 'hypergeo', U, L, z, tol, maxiter, check_mod, polynomial)
}

genhypergeo_series_cpp <- function(real_U, imag_U, real_L, imag_L, real_z, imag_z, tol, maxiter, check_mod, polynomial) {
    .Call('hypergeo_genhypergeo_series_cpp', PACKAGE = 'hypergeo', real_U, imag_U, real_L, imag_L, real_z, imag_z, tol, maxiter, check_mod, polynomial)
}

lanczos <- function(z) {
    .Call('hypergeo_lanczos', PACKAGE = 'hypergeo', z)
}

lanczos_cpp <- function(real, imag) {
    .Call('hypergeo_lanczos_cpp', PACKAGE = 'hypergeo', real, imag)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('hypergeo_RcppExport_registerCCallable', PACKAGE = 'hypergeo')
})
